name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  test:
    name: Run test-unit
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        ruby-version: [2.5, 2.6, 2.7, 3.0, 3.1]
        bundler-version: [2.3.18, 2.3.19, 2.3.20, 2.3.21, 2.3.22, 2.3.22, 2.3.23]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          bundler: ${{ matrix.bundler-version }}

      - name: Run tests
        run: bundle exec rake
